version: '3'
services:
  postgres_db:
    container_name: splitpay_db
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '$DATABASE_PASSWORD'
      POSTGRES_USER: '$DATABASE_USER'
      POSTGRES_DB: '$DATABASE_NAME'
  redis:
    container_name: splitpay_redis
    image: redis:alpine
    ports:
      - '6379:6379'
